name: Metadata Parser Validation for latest XSLT rules

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  list-conversion-settings:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-conversion-settings.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-conversion-settings
        run: echo "::set-output name=matrix::$(ls conversion-settings/*.json | sed 's/.*\///' | sed 's/\.[^.]*$//' | jq -R -s -c 'split("\n")[:-1]')"

  build:
    needs: list-conversion-settings
    strategy:
      matrix:
        version: ["v1.0", "beta"]
        settings: ${{ fromJson(needs.list-conversion-settings.outputs.matrix) }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.1.0
      with:
        dotnet-version: 8.0.x

    - name: Validate latest XSLT rules
      run: ./scripts/run-metadata-validation.ps1 -repoDirectory "${{ github.workspace }}" -version "${{ matrix.version }}" -platformName "${{ matrix.settings }}"
      shell: pwsh

    - name: Validate description with redocly
      uses: fluximus-prime/redocly-cli-github-action@v1
      continue-on-error: true # temporary workaround since our descriptions are invalid at the moment
      with:
        args: 'lint transformed_${{ matrix.version }}_${{ matrix.settings }}_metadata.yml --skip-rule operation-4xx-response --skip-rule no-server-trailing-slash --skip-rule no-unused-components --skip-rule security-defined --skip-rule info-license-url --skip-rule info-license --skip-rule no-empty-servers --skip-rule operation-summary --skip-rule tag-description --max-problems 1000'

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ matrix.version }}-${{ matrix.settings }}
        path: transformed_${{ matrix.version }}_${{ matrix.settings }}_metadata.yml
